version: '3'
services:
  web:
    build: .
    ports:
      - "3001:8080"
    environment:
      - DATABASE_URL=postgres://postgres:IyNfhnhGPmPSsXd0nkAo@containers-us-west-157.railway.app:6617/railway?sslmode=require
      - PORT=8080

