version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: awesomeproject-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - mynetwork
    volumes:
      - my_database_volume:/var/lib/postgresql/data

  app:
    build: .
    container_name: awesomeproject-app
    ports:
      - "3001:8080"
    environment:
      DB_URL: "postgresql://myuser:mysecretpassword@db:5432/mydatabase"
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  my_database_volume:

networks:
  mynetwork:
    driver: bridge